/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Tool {
    id: bigint;
    seoTitle?: string;
    pricingTag: string;
    name: string;
    createdAt: bigint;
    slug: string;
    officialLink: string;
    description: string;
    isPopular: boolean;
    updatedAt: bigint;
    isFeatured: boolean;
    seoKeywords?: string;
    category: string;
    seoDescription?: string;
    iconUrl: string;
}
export interface ToolSubmission {
    id: bigint;
    status: string;
    pricingTag: string;
    name: string;
    officialLink: string;
    submittedAt: bigint;
    description: string;
    category: string;
    iconUrl: string;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface PaginatedTools {
    tools: Array<Tool>;
    total: bigint;
    page: bigint;
    pageSize: bigint;
    totalPages: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCollection(name: string, toolIds: Array<bigint>, isFeatured: boolean): Promise<bigint>;
    addTool(name: string, iconUrl: string, description: string, category: string, pricingTag: string, officialLink: string, isFeatured: boolean, isPopular: boolean): Promise<bigint>;
    adminListTools(): Promise<Array<Tool>>;
    approveSubmission(submissionId: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUploadTools(toolsData: Array<Tool>): Promise<void>;
    deleteCollection(id: bigint): Promise<void>;
    deleteTool(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollection(id: bigint): Promise<{
        id: bigint;
        tools: Array<Tool>;
        name: string;
        isFeatured: boolean;
    } | null>;
    getFeaturedCollections(): Promise<Array<{
        id: bigint;
        tools: Array<Tool>;
        name: string;
        isFeatured: boolean;
    }>>;
    getFeaturedTools(): Promise<Array<Tool>>;
    getNewsletterEmails(): Promise<Array<string>>;
    getSimilarTools(toolId: bigint, limit: bigint): Promise<Array<Tool>>;
    getTool(id: bigint): Promise<Tool | null>;
    getToolBySlug(slug: string): Promise<Tool | null>;
    getToolsByCategory(category: string): Promise<Array<Tool>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listSubmissions(): Promise<Array<ToolSubmission>>;
    listTools(page: bigint, pageSize: bigint, filter: string | null, sortBy: string | null): Promise<PaginatedTools>;
    rejectSubmission(submissionId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTools(searchTerm: string): Promise<Array<Tool>>;
    setToolFeatured(id: bigint, featured: boolean): Promise<void>;
    submitTool(name: string, iconUrl: string, description: string, category: string, pricingTag: string, officialLink: string): Promise<bigint>;
    subscribeNewsletter(email: string): Promise<void>;
    updateCollection(id: bigint, name: string, toolIds: Array<bigint>, isFeatured: boolean): Promise<void>;
    updateTool(id: bigint, name: string, iconUrl: string, description: string, category: string, pricingTag: string, officialLink: string, isFeatured: boolean, isPopular: boolean): Promise<void>;
    updateToolSEO(id: bigint, seoTitle: string | null, seoDescription: string | null, seoKeywords: string | null): Promise<void>;
}
import type { PaginatedTools as _PaginatedTools, Tool as _Tool, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCollection(arg0: string, arg1: Array<bigint>, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCollection(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCollection(arg0, arg1, arg2);
            return result;
        }
    }
    async addTool(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean, arg7: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTool(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTool(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async adminListTools(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListTools();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListTools();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveSubmission(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSubmission(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUploadTools(arg0: Array<Tool>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUploadTools(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUploadTools(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCollection(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteTool(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTool(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTool(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollection(arg0: bigint): Promise<{
        id: bigint;
        tools: Array<Tool>;
        name: string;
        isFeatured: boolean;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedCollections(): Promise<Array<{
        id: bigint;
        tools: Array<Tool>;
        name: string;
        isFeatured: boolean;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedCollections();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedCollections();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedTools(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedTools();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedTools();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsletterEmails(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsletterEmails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsletterEmails();
            return result;
        }
    }
    async getSimilarTools(arg0: bigint, arg1: bigint): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSimilarTools(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSimilarTools(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTool(arg0: bigint): Promise<Tool | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTool(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTool(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToolBySlug(arg0: string): Promise<Tool | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolBySlug(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolBySlug(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToolsByCategory(arg0: string): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolsByCategory(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolsByCategory(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listSubmissions(): Promise<Array<ToolSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissions();
            return result;
        }
    }
    async listTools(arg0: bigint, arg1: bigint, arg2: string | null, arg3: string | null): Promise<PaginatedTools> {
        if (this.processError) {
            try {
                const result = await this.actor.listTools(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg3));
                return from_candid_PaginatedTools_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTools(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg3));
            return from_candid_PaginatedTools_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectSubmission(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectSubmission(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchTools(arg0: string): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTools(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTools(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setToolFeatured(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setToolFeatured(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setToolFeatured(arg0, arg1);
            return result;
        }
    }
    async submitTool(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTool(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTool(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async subscribeNewsletter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeNewsletter(arg0);
            return result;
        }
    }
    async updateCollection(arg0: bigint, arg1: string, arg2: Array<bigint>, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTool(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: boolean, arg8: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTool(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTool(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateToolSEO(arg0: bigint, arg1: string | null, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateToolSEO(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateToolSEO(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_PaginatedTools_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedTools): PaginatedTools {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Tool_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tool): Tool {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        id: bigint;
        tools: Array<_Tool>;
        name: string;
        isFeatured: boolean;
    }]): {
    id: bigint;
    tools: Array<Tool>;
    name: string;
    isFeatured: boolean;
} | null {
    return value.length === 0 ? null : from_candid_record_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tool]): Tool | null {
    return value.length === 0 ? null : from_candid_Tool_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tools: Array<_Tool>;
    name: string;
    isFeatured: boolean;
}): {
    id: bigint;
    tools: Array<Tool>;
    name: string;
    isFeatured: boolean;
} {
    return {
        id: value.id,
        tools: from_candid_vec_n1(_uploadFile, _downloadFile, value.tools),
        name: value.name,
        isFeatured: value.isFeatured
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tools: Array<_Tool>;
    total: bigint;
    page: bigint;
    pageSize: bigint;
    totalPages: bigint;
}): {
    tools: Array<Tool>;
    total: bigint;
    page: bigint;
    pageSize: bigint;
    totalPages: bigint;
} {
    return {
        tools: from_candid_vec_n1(_uploadFile, _downloadFile, value.tools),
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        totalPages: value.totalPages
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    seoTitle: [] | [string];
    pricingTag: string;
    name: string;
    createdAt: bigint;
    slug: string;
    officialLink: string;
    description: string;
    isPopular: boolean;
    updatedAt: bigint;
    isFeatured: boolean;
    seoKeywords: [] | [string];
    category: string;
    seoDescription: [] | [string];
    iconUrl: string;
}): {
    id: bigint;
    seoTitle?: string;
    pricingTag: string;
    name: string;
    createdAt: bigint;
    slug: string;
    officialLink: string;
    description: string;
    isPopular: boolean;
    updatedAt: bigint;
    isFeatured: boolean;
    seoKeywords?: string;
    category: string;
    seoDescription?: string;
    iconUrl: string;
} {
    return {
        id: value.id,
        seoTitle: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.seoTitle)),
        pricingTag: value.pricingTag,
        name: value.name,
        createdAt: value.createdAt,
        slug: value.slug,
        officialLink: value.officialLink,
        description: value.description,
        isPopular: value.isPopular,
        updatedAt: value.updatedAt,
        isFeatured: value.isFeatured,
        seoKeywords: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.seoKeywords)),
        category: value.category,
        seoDescription: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.seoDescription)),
        iconUrl: value.iconUrl
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tool>): Array<Tool> {
    return value.map((x)=>from_candid_Tool_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    id: bigint;
    tools: Array<_Tool>;
    name: string;
    isFeatured: boolean;
}>): Array<{
    id: bigint;
    tools: Array<Tool>;
    name: string;
    isFeatured: boolean;
}> {
    return value.map((x)=>from_candid_record_n16(_uploadFile, _downloadFile, x));
}
function to_candid_Tool_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tool): _Tool {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    seoTitle?: string;
    pricingTag: string;
    name: string;
    createdAt: bigint;
    slug: string;
    officialLink: string;
    description: string;
    isPopular: boolean;
    updatedAt: bigint;
    isFeatured: boolean;
    seoKeywords?: string;
    category: string;
    seoDescription?: string;
    iconUrl: string;
}): {
    id: bigint;
    seoTitle: [] | [string];
    pricingTag: string;
    name: string;
    createdAt: bigint;
    slug: string;
    officialLink: string;
    description: string;
    isPopular: boolean;
    updatedAt: bigint;
    isFeatured: boolean;
    seoKeywords: [] | [string];
    category: string;
    seoDescription: [] | [string];
    iconUrl: string;
} {
    return {
        id: value.id,
        seoTitle: value.seoTitle ? candid_some(value.seoTitle) : candid_none(),
        pricingTag: value.pricingTag,
        name: value.name,
        createdAt: value.createdAt,
        slug: value.slug,
        officialLink: value.officialLink,
        description: value.description,
        isPopular: value.isPopular,
        updatedAt: value.updatedAt,
        isFeatured: value.isFeatured,
        seoKeywords: value.seoKeywords ? candid_some(value.seoKeywords) : candid_none(),
        category: value.category,
        seoDescription: value.seoDescription ? candid_some(value.seoDescription) : candid_none(),
        iconUrl: value.iconUrl
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Tool>): Array<_Tool> {
    return value.map((x)=>to_candid_Tool_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
