/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tool = IDL.Record({
  'id' : IDL.Nat,
  'seoTitle' : IDL.Opt(IDL.Text),
  'pricingTag' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'officialLink' : IDL.Text,
  'description' : IDL.Text,
  'isPopular' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'isFeatured' : IDL.Bool,
  'seoKeywords' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'seoDescription' : IDL.Opt(IDL.Text),
  'iconUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const ToolSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'pricingTag' : IDL.Text,
  'name' : IDL.Text,
  'officialLink' : IDL.Text,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'iconUrl' : IDL.Text,
});
export const PaginatedTools = IDL.Record({
  'tools' : IDL.Vec(Tool),
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'totalPages' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCollection' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addTool' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'adminListTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'approveSubmission' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUploadTools' : IDL.Func([IDL.Vec(Tool)], [], []),
  'deleteCollection' : IDL.Func([IDL.Nat], [], []),
  'deleteTool' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollection' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'id' : IDL.Nat,
            'tools' : IDL.Vec(Tool),
            'name' : IDL.Text,
            'isFeatured' : IDL.Bool,
          })
        ),
      ],
      ['query'],
    ),
  'getFeaturedCollections' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'tools' : IDL.Vec(Tool),
            'name' : IDL.Text,
            'isFeatured' : IDL.Bool,
          })
        ),
      ],
      ['query'],
    ),
  'getFeaturedTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getNewsletterEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSimilarTools' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Tool)], ['query']),
  'getTool' : IDL.Func([IDL.Nat], [IDL.Opt(Tool)], ['query']),
  'getToolBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Tool)], ['query']),
  'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSubmissions' : IDL.Func([], [IDL.Vec(ToolSubmission)], ['query']),
  'listTools' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [PaginatedTools],
      ['query'],
    ),
  'rejectSubmission' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTools' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  'setToolFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'submitTool' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateCollection' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Bool],
      [],
      [],
    ),
  'updateTool' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateToolSEO' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tool = IDL.Record({
    'id' : IDL.Nat,
    'seoTitle' : IDL.Opt(IDL.Text),
    'pricingTag' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'officialLink' : IDL.Text,
    'description' : IDL.Text,
    'isPopular' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'isFeatured' : IDL.Bool,
    'seoKeywords' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'seoDescription' : IDL.Opt(IDL.Text),
    'iconUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const ToolSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'pricingTag' : IDL.Text,
    'name' : IDL.Text,
    'officialLink' : IDL.Text,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'iconUrl' : IDL.Text,
  });
  const PaginatedTools = IDL.Record({
    'tools' : IDL.Vec(Tool),
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'totalPages' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCollection' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addTool' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'adminListTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'approveSubmission' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUploadTools' : IDL.Func([IDL.Vec(Tool)], [], []),
    'deleteCollection' : IDL.Func([IDL.Nat], [], []),
    'deleteTool' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollection' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'id' : IDL.Nat,
              'tools' : IDL.Vec(Tool),
              'name' : IDL.Text,
              'isFeatured' : IDL.Bool,
            })
          ),
        ],
        ['query'],
      ),
    'getFeaturedCollections' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'tools' : IDL.Vec(Tool),
              'name' : IDL.Text,
              'isFeatured' : IDL.Bool,
            })
          ),
        ],
        ['query'],
      ),
    'getFeaturedTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getNewsletterEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSimilarTools' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Tool)],
        ['query'],
      ),
    'getTool' : IDL.Func([IDL.Nat], [IDL.Opt(Tool)], ['query']),
    'getToolBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Tool)], ['query']),
    'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSubmissions' : IDL.Func([], [IDL.Vec(ToolSubmission)], ['query']),
    'listTools' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [PaginatedTools],
        ['query'],
      ),
    'rejectSubmission' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTools' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
    'setToolFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'submitTool' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateCollection' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Bool],
        [],
        [],
      ),
    'updateTool' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateToolSEO' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };