/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PaginatedTools {
  'tools' : Array<Tool>,
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'totalPages' : bigint,
}
export interface Tool {
  'id' : bigint,
  'seoTitle' : [] | [string],
  'pricingTag' : string,
  'name' : string,
  'createdAt' : bigint,
  'slug' : string,
  'officialLink' : string,
  'description' : string,
  'isPopular' : boolean,
  'updatedAt' : bigint,
  'isFeatured' : boolean,
  'seoKeywords' : [] | [string],
  'category' : string,
  'seoDescription' : [] | [string],
  'iconUrl' : string,
}
export interface ToolSubmission {
  'id' : bigint,
  'status' : string,
  'pricingTag' : string,
  'name' : string,
  'officialLink' : string,
  'submittedAt' : bigint,
  'description' : string,
  'category' : string,
  'iconUrl' : string,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCollection' : ActorMethod<[string, Array<bigint>, boolean], bigint>,
  'addTool' : ActorMethod<
    [string, string, string, string, string, string, boolean, boolean],
    bigint
  >,
  'adminListTools' : ActorMethod<[], Array<Tool>>,
  'approveSubmission' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUploadTools' : ActorMethod<[Array<Tool>], undefined>,
  'deleteCollection' : ActorMethod<[bigint], undefined>,
  'deleteTool' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollection' : ActorMethod<
    [bigint],
    [] | [
      {
        'id' : bigint,
        'tools' : Array<Tool>,
        'name' : string,
        'isFeatured' : boolean,
      }
    ]
  >,
  'getFeaturedCollections' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'tools' : Array<Tool>,
        'name' : string,
        'isFeatured' : boolean,
      }
    >
  >,
  'getFeaturedTools' : ActorMethod<[], Array<Tool>>,
  'getNewsletterEmails' : ActorMethod<[], Array<string>>,
  'getSimilarTools' : ActorMethod<[bigint, bigint], Array<Tool>>,
  'getTool' : ActorMethod<[bigint], [] | [Tool]>,
  'getToolBySlug' : ActorMethod<[string], [] | [Tool]>,
  'getToolsByCategory' : ActorMethod<[string], Array<Tool>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSubmissions' : ActorMethod<[], Array<ToolSubmission>>,
  'listTools' : ActorMethod<
    [bigint, bigint, [] | [string], [] | [string]],
    PaginatedTools
  >,
  'rejectSubmission' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTools' : ActorMethod<[string], Array<Tool>>,
  'setToolFeatured' : ActorMethod<[bigint, boolean], undefined>,
  'submitTool' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'updateCollection' : ActorMethod<
    [bigint, string, Array<bigint>, boolean],
    undefined
  >,
  'updateTool' : ActorMethod<
    [bigint, string, string, string, string, string, string, boolean, boolean],
    undefined
  >,
  'updateToolSEO' : ActorMethod<
    [bigint, [] | [string], [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];